// <auto-generated />
using LogParserWebApi.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LogParserWebApi.Migrations
{
    [DbContext(typeof(LogContext))]
    [Migration("20180321100644_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LogParserWebApi.DomainModels.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Host");

                    b.Property<string>("HttpVersion");

                    b.Property<int?>("Length");

                    b.Property<string>("Method");

                    b.Property<string>("Route");

                    b.Property<int>("StatusCode");

                    b.Property<string>("UrlQueryParameters");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
